# Generated by Django 5.2.8 on 2025-12-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_ends_at',
            field=models.DateTimeField(blank=True, help_text='(Optional) Flash sale end time', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Special flash sale price (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_starts_at',
            field=models.DateTimeField(blank=True, help_text='(Optional) Flash sale start time', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False, help_text='Is this product in flash sale?'),
        ),
    ]
