# Generated by Django 5.2.8 on 2025-12-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_flash_ends_at_product_flash_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category thumbnail image', null=True, upload_to='categories/'),
        ),
    ]
